    <Resource name="jdbc/orcl" auth="Container"
              type="javax.sql.DataSource"
              driverClassName="oracle.jdbc.driver.OracleDriver"
              factory="org.apache.tomcat.dbcp.dbcp2.BasicDataSourceFactory"
              description="at ROOT.xml" 
              maxWait="-1"
              maxActive="10"
              maxTotal="500"
              initialSize="500"
              maxIdle="500"
              minIdle="500"
              username="TEST_OGG"
              password="TEST_OGG"
              testOnBorrow="true"
              validationQuery="select 1 from dual"
              url="jdbc:oracle:thin:@172.31.241.31:1527:SWGT9" />

    <Connector port="${tomcat.port.http}" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="${tomcat.port.https}"
               URIEncoding="${tomcat.connector.URIEncoding}"
               useBodyEncodingForURI="true"
               bindOnInit="false"
               maxThreads="500"
               server="Server" />
